### ISSUE TITLE
Svg Path distorted

### ISSUE THREAD

**Issue by sidharth016** [jpb12/react-tree-graph#1]
Hi, I am having a tad bit trouble integrating the graph. It is a great library indeed, But do i have to add some styling to the svg paths connecting the children?

<img width="374" alt="screen shot 2017-01-31 at 12 14 42 am" src="https://cloud.githubusercontent.com/assets/13831913/22436497/5a68681a-e74a-11e6-8bab-9d0056b2c63e.png">

**Comment by jpb12** [comment]
Hi, thanks for raising the first issue.

There's a demo integration of this at http://jpb12.github.io/tree-viewer/.  Have a look at the CSS that that is using.

That is what the tree looks like with no styling.  I haven't included any default styles in the library, though I probably should.  In particular, you want to set `fill: none;` on the links.

**Comment by jpb12** [comment]
There is now a CSS file included in the 1.2.0 release.
