### ISSUE TITLE
children with the same key

### ISSUE THREAD

**Issue by Northshoot** [jpb12/react-tree-graph#10]
Hey,

Currently, if to children have same name it results in an error

> Encountered two children with the same key

What would be a simplest way to implement separate sorting key and display name?

**Comment by jpb12** [comment]
You can already do this by setting a keyProp, as described in the docs.

| Property | Type | Mandatory | Default | Description |
|:---|:---|:---|:---|:---|
| `keyProp` | string | | "name" | The property on each node to use as a key. |

**Comment by Northshoot** [comment]
I saw that, but it does not work with the tree view example.
Setting the property causes error on (only) duplicate nodes

`TypeError: node.children is undefined`

**Comment by jpb12** [comment]
Can you add your code that's reproducing the issue?  The JSON date you're using and the props you're passing into the Tree component should be enough.

**Comment by Northshoot** [comment]
Without changing any code, this is the json

`export default {
    timestamp: '14/12/2016 22:00',
        name: 'Colour',
    sortvalue: 'Colour',
    children: [{
        name: 'Cyan',
        sortvalue: "Cyan_1",
    children: []
}, {
    name: 'Blue',
    sortvalue: 'Blue',
    children: [{
        name: 'Aquamarine',
        sortvalue: 'Aquamarine',

        children: []
    }, {
        name: 'Cyan',
        sortvalue: "Cyan_2",
        children: []
    }, {
        name: 'Navy',
        sortvalue: 'Navy',
        children: []
    }, {
        name: 'Turquoise',
        sortvalue: 'Turquoise',
        children: []
    }]
}, {
    name: 'Green',
        sortvalue: 'Green',
    children: []
}, {
    name: 'Purple',
        sortvalue: 'Purple',
    children: [{
        name: 'Indigo',
        sortvalue: 'Indigo',
        children: []
    }, {
        name: 'Violet',
        sortvalue: 'Violet',
        children: []
    }]
}]
};`

and this is the tree construct:

`<Tree
				animated
				data={root}
				height={this.props.height}
				width={this.props.width}
				 keyProp={'sortvalue'}
				gProps={{
					className: 'node',
					onClick: setActiveNode
				}}
				steps={30}/>`


With only addition of the 

` keyProp={'sortvalue'}`

**Comment by jpb12** [comment]
I've created an issue-10 branch with those changes and it works for me.  Are you sure your code has been rebuilt with your changes?  Can you try running `npm run build-dev -- --watch` or committing your changes to a fork somewhere?

**Comment by Northshoot** [comment]
hum, here is the form and included output when it crashes

https://github.com/Northshoot/tree-viewer/commits/master

**Comment by jpb12** [comment]
Those changes still work for me.  I suspect it's an issue with building the code.

**Comment by Linton-Samuel-Dawson** [comment]
@jpb12 I have kind of the same issue with `keyProp` ,  in [demo](https://github.com/jpb12/tree-viewer)   clicking on children nodes give an error that says `children.node` is undefined in `setClassName`.
