### ISSUE TITLE
linkClickHandler doesn't receive arguments

### ISSUE THREAD

**Issue by ronaldborman** [jpb12/react-tree-graph#2]
Hi, react-tree-graph looks like a nice, focused component. I'm experiencing some difficulty with a linkClickHandler though. The documentation states that it will receive source and target arguments, but I get undefined in both cases when the function is called. A nodeClickHandler, which receives a single node argument, does get the correct nodename.

Below is sample code (which is contained in the render method of a simple custom component). When for instance Node2 is clicked , the console output is 'Node2'. But with every link that is clicked, the output is 'undefined undefined'
```
let data = {name: 'Root', children: [{name: 'Node1', children: []}, {name: 'Node2',children: []}]};
let linkFn = function(source, target) {console.log(source, target)};
let nodeFn = function(node) {console.log(node)};

return (
  <Tree data={data} height={400} width={400} linkClickHandler={linkFn} nodeClickHandler={nodeFn} />
);
```

**Comment by jpb12** [comment]
This should be fixed in 1.2.2.

**Comment by jpb12** [comment]
Correction: 1.2.3.  I forgot to update the built files.

**Comment by jpb12** [comment]
Fixed.

**Comment by romanown** [comment]
can i see  in the description of the linkClickHandler? it is work?
