### ISSUE TITLE
Passing event object to click handlers

### ISSUE THREAD

**Issue by ronaldborman** [jpb12/react-tree-graph#3]
I have a use case where the event object, that the handleClick method of a Node or Link component receives, should be passed to the click handler. Right now it is discarded.

In a fork I have implemented this use case. Essentially it looks like this (in the case of a Node component):
```
handleClick(event) {
  this.props.onClick && this.props.onClick(this.props[this.props.keyProp], event);
}
```
Would this be a useful enhancement? And if so, should I create a pull request?

**Comment by jpb12** [comment]
Yes, please create a pull request.

**Comment by ronaldborman** [comment]
Done. See pull request [#4](https://github.com/jpb12/react-tree-graph/pull/4).

**Comment by ronaldborman** [comment]
Sorry, used the wrong button to add the comment. Reopening.
