### ISSUE TITLE
Using image for the node circle

### ISSUE THREAD

**Issue by Robert-Fish** [jpb12/react-tree-graph#32]
I'm trying to use an image(svg) as the image for the node circle and it won't work. I've tried

```
    <Tree
          data={this.props.scenes}
          height={400}
          width={800}
          nodeOffset={30}
          animated={true}
          svgProps={{
            className: "custom"
          }}
          circleProps={{ fill: "url(#img1)" }}
          gProps={{
            onClick: () => this.onClick()
          }}
    >
          <defs>
            <pattern id="img1" width="100%" height="200">
              <image href={Square} x="-50" y="0" width="300" height="267" />
            </pattern>
          </defs>
    </Tree>
```

**Comment by jpb12** [comment]
This is working for me. Are you including the css file? This sets a fill style on the circle, which overrides the fill attribute in the html, so it won't work if you include it.

**Comment by Robert-Fish** [comment]
It fills, but the circle doesn't change shape to that of the jpeg or get larger based. I want to use the jpeg instead of the circle shape

**Comment by nidhinkumar06** [comment]
@Robert-Fish Try the below code

`
<defs>
          <pattern id="image1" x="0" y="0" patternContentUnits="objectBoundingBox" height="100%" width="100%">
            <image
              height="1"
              weight="1"
              preserveAspectRatio="none"
              href='https://cdn.pixabay.com/photo/2013/07/12/17/41/computer-mouse-152249_960_720.png'>
              </image>
          </pattern>
        </defs>
`
