### ISSUE TITLE
setClassName error when  keyProps is set

### ISSUE THREAD

**Issue by Linton-Samuel-Dawson** [jpb12/react-tree-graph#34]
I'm testing [demo](https://github.com/jpb12/tree-viewer)  and I've set `keyProp` to `_id`.  now clicking on children nodes give an error that says `children.node` is undefined in `setClassName`.
this issue has been mentioned I in #10 but I don't think the problem is about using the same key.
this is data : 

        {
    name: 'Colour',
    _id: '41',
    children: [
        {
            name: 'Black',
            _id: '42',
            children: []
        },
        {
            name: 'Black',
            _id: '43',
            children: []
        },
        {
            name: 'Yellow',
            _id: '44',
            children: []
        }]
        }

**Comment by jpb12** [comment]
This is because you need to update the `getJson` method in `TreeContainer`.

```
getRoot(json) {
	if (json.name === this.props.activeNode) {
		return json;
	}
	for (let i = 0; i < json.children.length; i++) {
		let childJson = this.getRoot(json.children[i]);
		if (childJson) {
			return childJson;
		}
	}
	return false;
}
```

It's still using the `name` prop as an ID. You also need to change that to `_id`.
