### ISSUE TITLE
Support for drop event?

### ISSUE THREAD

**Issue by hopewise** [jpb12/react-tree-graph#40]
Is there a support for event of drag drop? ex: drag node and drop it on another node ( useful for move child to another parent.. ) so that we have ref for old parent, new parent and child ref

**Comment by hopewise** [comment]
Thanks for fast response
do you mean, I can do:

```
gProps={{
		onMouseUp
	}}
```

I will try, if I get all details in the passed event object, then, yes, it should be more than enough!
I will confirm here once I try it..

**Comment by jpb12** [comment]
From the [readme](https://github.com/jpb12/react-tree-graph#events):

> Event handlers in circleProps, gProp and textProps will be called with the node ID as an additional parameter.
> 
> `function(event, nodeId) { ... }`

**Comment by jpb12** [comment]
Closing. Feel free to reopen if you discover an issue with this.
