### ISSUE TITLE
How to change vertical distance between nodes?

### ISSUE THREAD

**Issue by CathySha** [jpb12/react-tree-graph#42]
I can use react-tree-graph to display my tree now!
But each layer of the tree has too many nodes, the nodes are very close vertically.

Now I can only solve this problem by setting height of `<APP>` like 
`<App value={data} high={3000}/>`.

Is there any other ways to set the smallest distance between nodes vertically?

**Comment by jpb12** [comment]
The only way to increase the distance is to increase the height, or reduce the number of nodes.
