### ISSUE TITLE
How to get 'value' of tree node?

### ISSUE THREAD

**Issue by CathySha** [jpb12/react-tree-graph#43]
The structure of my tree is:
````
node0
{
     'name': 'P1'
     'type': 'Project'
     'value': [......]
     'children': [node1, node2, ......]
}
````
 How can I get `value` of the node when I click on the node?
Thank you!

**Comment by jpb12** [comment]
There is an example of this in the [tree-viewer](https://github.com/jpb12/tree-viewer/blob/master/Components/treeContainer.js#L20-L31) demo.
