### ISSUE TITLE
Make a child node as parent node to view details

### ISSUE THREAD

**Issue by Pratyush1197** [jpb12/react-tree-graph#53]
How can we make it possible that on clicking on any child node that particular node act as parent so we can view the detailed branch of that particular node and add reset button to bring everything back to default. Can you please tell me how to implement this on my own code?

**Comment by jpb12** [comment]
This is how the [example](https://jpb12.github.io/tree-viewer/) works. The code for that is also on [github](https://github.com/jpb12/tree-viewer).
