### ISSUE TITLE
gProps assumes className passed in

### ISSUE THREAD

**Issue by hnry** [jpb12/react-tree-graph#54]
Whenever you pass in `gProps` => `gProps={{ onClick: this.click }}`, it also assumes you meant to pass in `className` too.

I'm guessing the implementation just does a `props = gProps` and not a merge `Object.assign(props, gProps)` (replace only what's new).

It has the side effect of overriding the default `.node` class.

Not a big deal, but I don't think it was intended, and I don't know what other gotchas that might bring up.

Can see example @ https://jpb12.github.io/react-tree-graph/#clicking , all other graphs have the default '.node' class except the click, and custom node props example.

Btw great library.

**Comment by jpb12** [comment]
Should be fixed in 4.0.1
