### ISSUE TITLE
doesn't work tree rotation on Safari

### ISSUE THREAD

**Issue by alexey-khisamutdinov** [jpb12/react-tree-graph#59]
In SVG 1.1 <svg> elements did not support transform attributes. In SVG 2 it is proposed that they should.
Chrome and Firefox implement this part of the SVG 2 specification, Safari does not yet do so and IE11 never will.

![image](https://user-images.githubusercontent.com/25253567/67361025-59715600-f51c-11e9-9485-217d17307524.png)

A fix or a workaround is highly appreciated.

**Comment by jpb12** [comment]
CSS transforms will work in safari.

```css
svg {
    transform: rotate(90deg);
}
```
