### ISSUE TITLE
Unable to add other events besides onClick

### ISSUE THREAD

**Issue by bdparrish** [jpb12/react-tree-graph#62]
I have tried to add both `onContextclick` and `onDblclick` but the functions are not being called and I don't see them attached to the `g` node.

I am looking for a solution to either have a custom button next to the text or allow for some other mouse gesture to have two different actions for a node.

**Comment by jpb12** [comment]
Which version are you using? If it's the latest (4.0.1), can you attach the code where you render the tree.

> I don't see them attached to the g node.

Just to confirm, are you checking in something like the react developer tools and not the default DOM inspector.

**Comment by bdparrish** [comment]
Yes, `"react-tree-graph": "^4.0.1",` ...

I am looking at the `g` object passed along on the `onClick` event that I also defined.

```
      <Tree
        data={data}
        nodeRadius={10}
        gProps={{
          className: 'node',
          onClick: handleClick,
          onContextclick: handleRightClick,
        }}
        keyProp="path"
        labelProp="name"
      />
```

**Comment by jpb12** [comment]
I've added right click to the [event example](https://jpb12.github.io/react-tree-graph/#clicking), and it's working for me, so I don't think this is an issue with the library.

**Comment by jpb12** [comment]
From your code:
`onContextClick`, not `onContextclick`.
Should be `onDoubleClick` for double click.

The full list is [here](https://reactjs.org/docs/events.html#mouse-events).

**Comment by bdparrish** [comment]
Just an FYI, double clicking still calls the click too, so both events are performed.

**Comment by jpb12** [comment]
You can prevent the browser menu showing by calling `event.preventDefault()`
