### ISSUE TITLE
keyProp blocks getting onClick node parameter

### ISSUE THREAD

**Issue by Osheo** [jpb12/react-tree-graph#64]
Hi! I have problem with one task. After onClick event on node I have to display popup with user data from tree. First problem is when I add keyProp: "example-1" to data tree object then onClick event parameter node is undefined. When I delete keyProp from object, it works correctly but it keyProp in my case is required. Second problem is how to pass to onClick event parameter with whole object data? Not only node name but also id, username etc. Thank for help! ;)

Example of my object:
`{
          id: 2,
          username: "test123",
          firstName: "test",
          lastName: "test",
          id_parent: 6,
          role: "user",
          name: "test test",
          pathProps: { className: "test-link link" },
          circleProps: { className: "test-circle" },
          keyProp: "test-test",
          children: [
            {
              name: "Aquamarine",
              keyProp: "test-test-1",
              children: []
            },
            {
              name: "Cyan",
              keyProp: "test-test-2",
              children: []
            },
            {
              name: "Navy",
              keyProp: "test-test-3",
              children: []
            },
            {
              name: "Turquoise",
              keyProp: "test-test-3",
              children: []
            }
          ]
        },`

**Comment by jpb12** [comment]
You're misusing `keyProp`. `keyProp` isn't the identifier, it is the name of the property that should be used as the identifier. By default, the value is `name`, so the `name` property will be used as the identifier.

The only time you would need to change this is if you have multiple nodes with the same name. In this case, you would set `keyProp` as something like `id` and then set a unique `id` property on each node.

By setting `keyProp` to test-test, the code is expecting to be able to use the result of this.props[test-test] as a unique identifier.

**Comment by jpb12** [comment]
> Second problem is how to pass to onClick event parameter with whole object data? Not only node name but also id, username etc.

Since you have the unique identifier, you should be able to use it to find the original node in your data object. There's an example of this approach in the [tree-viewer](https://github.com/jpb12/tree-viewer/blob/master/Components/treeContainer.js#L20-L31) demo repo.
