### ISSUE TITLE
Add zoom functionality

### ISSUE THREAD

**Issue by flordonorte** [jpb12/react-tree-graph#68]
I am trying to trigger zoom in the tree with d3-zoom, but for that d3 needs to have a g element surrounding all elements, like:
`<svg><g>elements</g></svg>`
where we can apply transforms with it.

Is any way to zoom the tree?

**Comment by jpb12** [comment]
Can you apply the transform to the `<svg>` element?

**Comment by flordonorte** [comment]
I tried it but when applying the zoom to the SVG element, the shapes inside the tree get out of the SVG container, like the figures have no boundaries, when applying a scale or a translate.
The official documentation:
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform

**Comment by jpb12** [comment]
css `overflow:hidden` should fix that.

The example on your second link is adding the transform to the svg.

**Comment by jpb12** [comment]
If you wrap the `svg` in a `div` and apply the `overflow:hidden` to the div, that should work.
You could also use `viewBox` to zoom and pan, but doesn't look like d3 zoom supports that.
If neither of these work, I can make a change for the next release.

**Comment by flordonorte** [comment]
Did you have any date for the upgrade?

**Comment by flordonorte** [comment]
Thanks for the improvement! It will help me a lot! :)
