### ISSUE TITLE
Increasing width of text

### ISSUE THREAD

**Issue by stheobald** [jpb12/react-tree-graph#69]
Is it possible to alter the visible width of the 'text' elements in a node?

I have some long strings I'd like to display, but they are visibly truncated, and I don't see a CSS fix for this. Actually - I can't see anywhere in the source that's limiting the visible width either.

I've made a quick example here based on the docs: https://codesandbox.io/s/practical-newton-pq7df

**Comment by jpb12** [comment]
There is no limit to the width of the text. However, the text must fit within the space of the SVG. For text on leaf nodes, it must fit within the right margin, which is set by default to 150px, but can be changed with the `margins` prop.

See: https://codesandbox.io/s/practical-morning-vxljb

**Comment by stheobald** [comment]
Thanks - that solves it perfectly.
