### ISSUE TITLE
Default configuration doesn't render graph correctly

### ISSUE THREAD

**Issue by atshakil** [jpb12/react-tree-graph#7]
The following graph was rendered using the default configuration of version `2.0.0`
![1](https://user-images.githubusercontent.com/14325309/31820104-82328736-b5c1-11e7-98c0-cd6732f84eba.png)

**Comment by jpb12** [comment]
See #1

**Comment by jpb12** [comment]
For clarification, you need to apply styles yourself.  There is a default css file you can include, which is mentioned in the [readme](https://github.com/jpb12/react-tree-graph#usage).
