### ISSUE TITLE
Is there a way for 2+ nodes to point to same child?

### ISSUE THREAD

**Issue by miguel-krasamo** [jpb12/react-tree-graph#78]
I have some nodes that rely on the same child, I thought that being the same name they would redirect to the same node, but it's not. 

Is this possible?

**Comment by jpb12** [comment]
No, a child cannot have multiple parent nodes. You would need to duplicate the child if you wanted it to appear under both nodes in the tree, and it will appear separately.

Have a look at some other examples using d3. There may be one that is a better fit for your data than a tree.
