### ISSUE TITLE
changing orientation

### ISSUE THREAD

**Issue by Northshoot** [jpb12/react-tree-graph#8]
Hey,

what would be the way to change the orientation of the tree?

**Comment by jpb12** [comment]
You can add a [transform](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transforml) to the root SVG element.  Is that enough for you?

**Comment by jpb12** [comment]
The [examples](https://jpb12.github.io/react-tree-graph/#vertical) page now contains an example of rotating to display vertically.
