### ISSUE TITLE
Demo not working properly

### ISSUE THREAD

**Issue by hur-kyuh-leez** [jpb12/react-tree-graph#82]
hi, jpb12
thanks for making an awesome-looking tree graph.
I found a bug in your [demo](https://jpb12.github.io/tree-viewer/). 
It's not working properly.
Clicking node or typing in the filter search box, the graph is not available anymore.

I tried the demo in up-to-date chrome, firefox, and opera.

**Comment by jpb12** [comment]
Should be working now
https://github.com/jpb12/tree-viewer/commit/8881381042316e2c1dc78b20cd9e0aba29318fd8
