### ISSUE TITLE
Straight line path function for links

### ISSUE THREAD

**Issue by petkesrichard** [jpb12/react-tree-graph#84]
Hi,
What is the function to have straight lines as links between nodes?
pathFunc={function noRefCheck(){}}

Thanks in advance!

**Comment by jpb12** [comment]
The [source code](https://github.com/jpb12/react-tree-graph/tree/gh-pages/code) for all the examples is available on github, including the [straight line function](https://github.com/jpb12/react-tree-graph/blob/gh-pages/code/tree/path.js#L19).

```js
(x1, y1, x2, y2) => `M${y1},${x1} ${y2},${x2}`
```
