### ISSUE TITLE
Set hardcoded position (x, y) of the Node

### ISSUE THREAD

**Issue by dax4y** [jpb12/react-tree-graph#86]
Hi,

is there any way that i can set the node position and path will be automatically linked and other nodes automatically adapted on this set?

e.g. i want to make only straight middle line of years (must be straight) and others child nodes will be automatically calculated from one and another year node.

<img width="657" alt="years" src="https://user-images.githubusercontent.com/78612937/223832050-15b346fd-97a0-4eb2-b7a6-8c9040ffdf1f.png">

example: the blue line must be straight

Thanks.

**Comment by jpb12** [comment]
The positioning of nodes within the tree is handled by [d3-hierarchy](https://github.com/d3/d3-hierarchy#tree), which does not support this. You could raise an issue there but I don't think it's likely to be added. The algorithm is designed to produce an optimal spacing of nodes for a given space, so won't produce 

You could do this _hackily_ by balancing the tree yourself, adding extra nodes as necessary to make it symmetrical. If you set a class on the added nodes, you can then hide them in CSS. This may result in large empty spaces in your tree.
```js
{
    name: 'something-unique',
    nodeProps: { className: 'hidden' },
    pathProps: { className: 'hidden' }
}
```
